# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 402)
        MainWindow.setMaximumSize(QtCore.QSize(1666571, 1666571))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.hName = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hName.setFont(font)
        self.hName.setObjectName("hName")
        self.gridLayout.addWidget(self.hName, 3, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 1)
        self.vEmail = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vEmail.setFont(font)
        self.vEmail.setObjectName("vEmail")
        self.gridLayout.addWidget(self.vEmail, 4, 1, 1, 1)
        self.hEmail = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hEmail.setFont(font)
        self.hEmail.setObjectName("hEmail")
        self.gridLayout.addWidget(self.hEmail, 4, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 1, 1, 1)
        self.vPhone = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vPhone.setFont(font)
        self.vPhone.setObjectName("vPhone")
        self.gridLayout.addWidget(self.vPhone, 5, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 5)
        self.submitbutton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitbutton.sizePolicy().hasHeightForWidth())
        self.submitbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submitbutton.setFont(font)
        self.submitbutton.setObjectName("submitbutton")
        self.gridLayout.addWidget(self.submitbutton, 7, 1, 1, 1)
        self.hPhone = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hPhone.setFont(font)
        self.hPhone.setObjectName("hPhone")
        self.gridLayout.addWidget(self.hPhone, 5, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 2, 3, 1)
        self.vName = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vName.setFont(font)
        self.vName.setObjectName("vName")
        self.gridLayout.addWidget(self.vName, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkOutBtn = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkOutBtn.sizePolicy().hasHeightForWidth())
        self.checkOutBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkOutBtn.setFont(font)
        self.checkOutBtn.setObjectName("checkOutBtn")
        self.gridLayout_2.addWidget(self.checkOutBtn, 1, 0, 1, 1)
        self.visitorInsideView = QtWidgets.QTableView(self.tab_2)
        self.visitorInsideView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.visitorInsideView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.visitorInsideView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.visitorInsideView.setObjectName("visitorInsideView")
        self.gridLayout_2.addWidget(self.visitorInsideView, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionCheck_In = QtWidgets.QAction(MainWindow)
        self.actionCheck_In.setObjectName("actionCheck_In")
        self.actionCheck_Out = QtWidgets.QAction(MainWindow)
        self.actionCheck_Out.setObjectName("actionCheck_Out")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visitor Form - SummerGeeks 2020"))
        self.label_3.setText(_translate("MainWindow", "Phone"))
        self.label.setText(_translate("MainWindow", "Email"))
        self.label_5.setText(_translate("MainWindow", "Email"))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_8.setText(_translate("MainWindow", "Host"))
        self.label_6.setText(_translate("MainWindow", "Phone"))
        self.label_7.setText(_translate("MainWindow", "Visitor"))
        self.submitbutton.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Check In"))
        self.checkOutBtn.setText(_translate("MainWindow", "Check Out"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Check Out"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCheck_In.setText(_translate("MainWindow", "Check In"))
        self.actionCheck_Out.setText(_translate("MainWindow", "Check Out"))

